// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prados.Web.Data;

namespace Prados.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201006162700_CompleteDb1")]
    partial class CompleteDb1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prados.Web.Data.Entities.Aniostbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ani_Descripcion");

                    b.HasKey("Id");

                    b.ToTable("Aniostbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Managerstbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Managerstbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.MarcasAutostbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mar_Descripcion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("MarcasAutostbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Mesestbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mes_Descripcion");

                    b.HasKey("Id");

                    b.ToTable("Mesestbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Negociostbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Neg_Descripcion");

                    b.Property<string>("Neg_Direccion");

                    b.Property<string>("Neg_Email");

                    b.Property<string>("Neg_Estado")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("Neg_FechaCreacion");

                    b.Property<string>("Neg_Nombre");

                    b.Property<string>("Neg_Telefono");

                    b.Property<int?>("PropietariosId");

                    b.HasKey("Id");

                    b.HasIndex("PropietariosId");

                    b.ToTable("Negociostbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Pagostbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnioId");

                    b.Property<int?>("MesId");

                    b.Property<string>("PAG_ESTADO")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("PAG_FECHACREACION");

                    b.Property<DateTime>("PAG_FECHAPAGADO");

                    b.Property<int?>("PropietarioId");

                    b.Property<int?>("PuntodePagoId");

                    b.Property<int?>("ValId");

                    b.HasKey("Id");

                    b.HasIndex("AnioId");

                    b.HasIndex("MesId");

                    b.HasIndex("PropietarioId");

                    b.HasIndex("PuntodePagoId");

                    b.HasIndex("ValId");

                    b.ToTable("Pagostbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Productostbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NegocioId");

                    b.Property<string>("Pro_Estado")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("Pro_FechaCreacion");

                    b.Property<string>("Pro_Nombre");

                    b.Property<string>("Pro_Precio");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Productostbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Propietariostbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TiposViviendatblId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TiposViviendatblId");

                    b.HasIndex("UserId");

                    b.ToTable("Propietariostbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.PuntosPagotbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pun_Descripcion");

                    b.HasKey("Id");

                    b.ToTable("PuntosPagotbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.TiposViviendatbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tip_Descripcion");

                    b.HasKey("Id");

                    b.ToTable("TiposViviendatbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Userstbl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("Pro_Apellidos")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pro_Identificacion")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Pro_Lote")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("Pro_Nombres")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pro_Observaciones");

                    b.Property<string>("Pro_Telefono")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Pro_TipoIdentificacion")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int?>("Pro_TipoViviendaId");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Pro_TipoViviendaId");

                    b.ToTable("Userstbl");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Valorestbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Val_Estado")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("Val_FechaCreacion");

                    b.Property<string>("Val_Valor");

                    b.HasKey("Id");

                    b.ToTable("Valorestbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Vehiculostbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<int?>("MarcasAutostblId");

                    b.Property<int?>("PropietarioId");

                    b.Property<DateTime>("Veh_Born");

                    b.Property<string>("Veh_Codigo")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("Veh_Detalles");

                    b.Property<string>("Veh_Estado");

                    b.Property<string>("Veh_Placa")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.HasIndex("MarcasAutostblId");

                    b.HasIndex("PropietarioId");

                    b.ToTable("Vehiculostbls");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Negociostbl", b =>
                {
                    b.HasOne("Prados.Web.Data.Entities.Propietariostbl", "Propietarios")
                        .WithMany("Negocio")
                        .HasForeignKey("PropietariosId");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Pagostbl", b =>
                {
                    b.HasOne("Prados.Web.Data.Entities.Aniostbl", "Anio")
                        .WithMany("Pagos")
                        .HasForeignKey("AnioId");

                    b.HasOne("Prados.Web.Data.Entities.Mesestbl", "Mes")
                        .WithMany("Pagos")
                        .HasForeignKey("MesId");

                    b.HasOne("Prados.Web.Data.Entities.Propietariostbl", "Propietario")
                        .WithMany("Pagos")
                        .HasForeignKey("PropietarioId");

                    b.HasOne("Prados.Web.Data.Entities.PuntosPagotbl", "PuntodePago")
                        .WithMany("Pagos")
                        .HasForeignKey("PuntodePagoId");

                    b.HasOne("Prados.Web.Data.Entities.Valorestbl", "Val")
                        .WithMany("Pagos")
                        .HasForeignKey("ValId");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Productostbl", b =>
                {
                    b.HasOne("Prados.Web.Data.Entities.Negociostbl", "Negocio")
                        .WithMany("Producto")
                        .HasForeignKey("NegocioId");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Propietariostbl", b =>
                {
                    b.HasOne("Prados.Web.Data.Entities.TiposViviendatbl")
                        .WithMany("Propietarios")
                        .HasForeignKey("TiposViviendatblId");

                    b.HasOne("Prados.Web.Data.Entities.Userstbl", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Userstbl", b =>
                {
                    b.HasOne("Prados.Web.Data.Entities.TiposViviendatbl", "Pro_TipoVivienda")
                        .WithMany()
                        .HasForeignKey("Pro_TipoViviendaId");
                });

            modelBuilder.Entity("Prados.Web.Data.Entities.Vehiculostbl", b =>
                {
                    b.HasOne("Prados.Web.Data.Entities.MarcasAutostbl")
                        .WithMany("Vehiculos")
                        .HasForeignKey("MarcasAutostblId");

                    b.HasOne("Prados.Web.Data.Entities.Propietariostbl", "Propietario")
                        .WithMany("Vehiculos")
                        .HasForeignKey("PropietarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
